name: Deploy Obsidian Export

on:
  push:
    branches:
      - main
    paths:
      - 'HTML Exports/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ðŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Redirect Index
        run: |
          cd "HTML Exports"
          target_file=$(ls einf*hrung*.html 2>/dev/null | head -n 1)
          
          if [ -n "$target_file" ]; then
            echo "Creating redirect index pointing to $target_file"
            
            # Ensure EOF has no spaces after it and is at the start of the line
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url='$target_file'" />
              <title>Redirecting...</title>
            </head>
            <body>
              <p>Redirecting to <a href="$target_file">$target_file</a></p>
            </body>
          </html>
          EOF
          else
            echo "Error: No export file found."
            exit 1
          fi

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: v132927.goserver.host
          username: allesman
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./HTML Exports/
          server-dir: ./eidi/
          delete-missing: true
